name       : budgie-desktop
version    : 10.5.3
release    : 237
source     :
    - https://getsol.us/sources/budgie-desktop-v10.5.3.tar.xz : 878f4e6460c29740bf633c3b11ba97bcb788068c1460f82569938af2f1633b25
license    :
    - GPL-2.0-only
    - LGPL-2.1-only
summary    : Budgie Desktop is the flagship desktop experience developed by the Solus team.
description: |
    Budgie Desktop is the flagship desktop experience developed by the Solus team.
component  : desktop.budgie
builddeps  :
    - pkgconfig(accountsservice)
    - pkgconfig(alsa)
    - pkgconfig(gnome-bluetooth-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gnome-settings-daemon)
    - pkgconfig(gtk-doc)
    - pkgconfig(ibus-1.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libgnome-menu-3.0)
    - pkgconfig(libmutter-8)
    - pkgconfig(libnotify)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(libpulse-mainloop-glib)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(upower-glib)
    - budgie-screensaver # Required at configure time to ensure we have a proper configuration of budgie-desktop
    - vala
    - sassc
rundeps    :
    - budgie-desktop-view
    - budgie-screensaver
    - gnome-session
    - gnome-settings-daemon
    - network-manager-applet
    - xdotool
setup      : |
    %meson_configure -Dwith-stateless=true
build      : |
    %ninja_build
install    : |
    %ninja_install
