name       : budgie-desktop
version    : 10.2.5
release    : 84
source     :
    - https://solus-project.com/sources/budgie-desktop-10.2.5.tar.xz : 440a811bb15031f1cc9f26e46128ea3d74f7666a93cfcd3dae521bcc0d6b72f5
license    :
    - GPL-2.0
    - LGPL-2.1
summary    : Budgie Desktop
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libpulse-mainloop-glib)
    - pkgconfig(libmutter)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(upower-glib)
    - pkgconfig(libgnome-menu-3.0)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gnome-bluetooth-1.0)
    - pkgconfig(gtk-doc)
    - vala
rundeps    :
    - gnome-session
    - gnome-settings-daemon
    - gnome-control-center
    - gnome-screensaver
ccache     : no
description: |
    Budgie Desktop
setup      : |
    %patch -p1 < $pkgfiles/0001-Revert-raven-Restore-lightdm-only-screen-locking.patch
    %patch -p1 < $pkgfiles/0002-raven-Actually-update-the-date-so-I-don-t-miss-my-re.patch
    %configure --disable-static --enable-stateless
build      : |
    %make
install    : |
    %make_install
