name        : budgie-desktop
version     : 10.2.4
release     : 71
source     :
    - https://github.com/solus-project/budgie-desktop/releases/download/v10.2.4/budgie-desktop-10.2.4.tar.xz : b01e7be9349cbc26cd77db74a0c138d21c31d8bad21a02b31828014b416256f7
license     :
    - GPL-2.0
summary     : Budgie Desktop
builddeps   :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libpulse-mainloop-glib)
    - pkgconfig(libmutter)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(upower-glib)
    - pkgconfig(libgnome-menu-3.0)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gsettings-desktop-schemas)
    - vala
rundeps     :
    - gnome-session
    - gnome-settings-daemon
    - gnome-control-center
ccache      : no
description : |
    Budgie Desktop
setup      : |
    %patch -p1 < $pkgfiles/0001-raven-Restore-lightdm-only-screen-locking.patch
    %patch -p1 < $pkgfiles/default-pins.patch
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
