name       : budgie-desktop
version    : '10.4'
release    : 170
source     :
    - git|https://github.com/budgie-desktop/budgie-desktop.git : 36667bcb75362332278fa27a0428cf5cb0d27043
license    :
    - GPL-2.0
    - LGPL-2.1
summary    : Budgie Desktop
component  : desktop.budgie
builddeps  :
    - pkgconfig(accountsservice)
    - pkgconfig(gnome-bluetooth-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gnome-settings-daemon)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk-doc)
    - pkgconfig(ibus-1.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libgnome-menu-3.0)
    - pkgconfig(libmutter-2)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(libpulse-mainloop-glib)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(upower-glib)
    - pkgconfig(xtst)
    - vala
    - sassc
rundeps    :
    - gnome-session
    - gnome-settings-daemon
    - gnome-screensaver
description: |
    Budgie Desktop
setup      : |
    %meson_configure -Dwith-stateless=true -Dwith-desktop-icons=nautilus
build      : |
    %meson_build
install    : |
    %meson_install
