name        : budgie-desktop
version     : 10.1
release     : 62
source     :
    - https://github.com/solus-project/budgie-desktop/releases/download/v10.1/budgie-desktop-10.1.tar.xz : f8f0245ffb02f6ec1789c62b30d5c5880af7bd61e9e83aed74b8e88a38929fc3
license     :
    - GPL-2.0
summary     : Budgie Desktop
builddeps   :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libpulse-mainloop-glib)
    - pkgconfig(libmutter)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(upower-glib)
    - pkgconfig(libgnome-menu-3.0)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gsettings-desktop-schemas)
    - vala
rundeps     :
    - gnome-session
    - gnome-settings-daemon
    - gnome-control-center
ccache      : no
description : |
    Budgie Desktop
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
