name        : budgie-desktop
version     : 10.2.3
release     : 67
source     :
    - https://github.com/solus-project/budgie-desktop/releases/download/v10.2.3/budgie-desktop-10.2.3.tar.xz : 2556a75220dfde4fd75e80a43a2d07575cea887ad0d4e169acb48e135707beac
license     :
    - GPL-2.0
summary     : Budgie Desktop
builddeps   :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libpulse-mainloop-glib)
    - pkgconfig(libmutter)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(upower-glib)
    - pkgconfig(libgnome-menu-3.0)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gsettings-desktop-schemas)
    - vala
rundeps     :
    - gnome-session
    - gnome-settings-daemon
    - gnome-control-center
ccache      : no
description : |
    Budgie Desktop
setup      : |
    %patch -p1 < $pkgfiles/0001-applets-tray-Force-the-correct-colours.patch
    %patch -p1 < $pkgfiles/0002-applets-tray-Fix-default-icon-size-so-that-first-ico.patch
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
