name       : budgie-desktop
version    : '10.4'
release    : 148
source     :
    - https://github.com/budgie-desktop/budgie-desktop/releases/download/v10.4/budgie-desktop-10.4.tar.xz : 17da8efe56a73426117f89eed8f2a1236c592042acb8d3fec063b24ebe124245
license    :
    - GPL-2.0
    - LGPL-2.1
summary    : Budgie Desktop
component  : desktop.budgie
builddeps  :
    - pkgconfig(accountsservice)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libpulse-mainloop-glib)
    - pkgconfig(libmutter-1)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(upower-glib)
    - pkgconfig(libgnome-menu-3.0)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gnome-bluetooth-1.0)
    - pkgconfig(gtk-doc)
    - pkgconfig(ibus-1.0)
    - pkgconfig(xtst)
    - vala
    - meson
    - sassc
rundeps    :
    - gnome-session
    - gnome-settings-daemon
    - gnome-screensaver
description: |
    Budgie Desktop
setup      : |
    %meson_configure -Dwith-stateless=true
build      : |
    %meson_build
install    : |
    # meson mandates utf8
    export LANG=en_US.utf8
    export LC_ALL=en_US.utf8
    %meson_install
