name       : budgie-desktop
version    : 10.5.2
release    : 231
source     :
    - git|https://github.com/solus-project/budgie-desktop.git : 481e9bd25afaa4f35ae9db6fdde28d17ec29cbe9
license    :
    - GPL-2.0-only
    - LGPL-2.1-only
summary    : Budgie Desktop is the flagship desktop experience developed by the Solus team.
description: |
    Budgie Desktop is the flagship desktop experience developed by the Solus team.
component  : desktop.budgie
builddeps  :
    - pkgconfig(accountsservice)
    - pkgconfig(alsa)
    - pkgconfig(gnome-bluetooth-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gnome-settings-daemon)
    - pkgconfig(gtk-doc)
    - pkgconfig(ibus-1.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libgnome-menu-3.0)
    - pkgconfig(libmutter-7)
    - pkgconfig(libnotify)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(libpulse-mainloop-glib)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(upower-glib)
    - vala
    - sassc
rundeps    :
    - budgie-desktop-view
    - gnome-session
    - gnome-settings-daemon
    - gnome-screensaver
    - network-manager-applet
setup      : |
    %meson_configure -Dwith-stateless=true
build      : |
    %ninja_build
install    : |
    %ninja_install
