name       : budgie-desktop
version    : '10.6'
release    : 241
source     :
    - https://github.com/BuddiesOfBudgie/budgie-desktop/releases/download/v10.6/budgie-desktop-v10.6.tar.xz : ba297a10b547e6d7bf164406750b5c5dae98a7524978b30b4ad3cba9624def9e
license    :
    - GPL-2.0-only
    - LGPL-2.1-only
summary    : Budgie Desktop is the flagship desktop experience developed by the Solus team.
description: |
    Budgie Desktop is the flagship desktop experience developed by the Solus team.
component  : desktop.budgie
builddeps  :
    - pkgconfig(accountsservice)
    - pkgconfig(alsa)
    - pkgconfig(gnome-bluetooth-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gnome-settings-daemon)
    - pkgconfig(gtk-doc)
    - pkgconfig(ibus-1.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libgnome-menu-3.0)
    - pkgconfig(libmutter-9)
    - pkgconfig(libnotify)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(libpulse-mainloop-glib)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(upower-glib)
    - budgie-screensaver # Required at configure time to ensure we have a proper configuration of budgie-desktop
    - vala
    - sassc
rundeps    :
    - budgie-control-center
    - budgie-desktop-view
    - budgie-screensaver
    - gnome-session
    - gnome-settings-daemon
    - network-manager-applet
    - xdotool
setup      : |
    %meson_configure -Dwith-stateless=true
build      : |
    %ninja_build
install    : |
    %ninja_install
