name       : budgie-desktop
version    : 10.3.1
release    : 131
source     :
    - https://github.com/budgie-desktop/budgie-desktop/releases/download/v10.3.1/budgie-desktop-10.3.1.tar.xz : c19a5ac3f5cd1d142a87efded62f8a1750eb2af25102ff151da9201353a18b84
license    :
    - GPL-2.0
    - LGPL-2.1
summary    : Budgie Desktop
component  : desktop.budgie
builddeps  :
    - pkgconfig(accountsservice)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libpulse-mainloop-glib)
    - pkgconfig(libmutter-0)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(upower-glib)
    - pkgconfig(libgnome-menu-3.0)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gnome-bluetooth-1.0)
    - pkgconfig(gtk-doc)
    - pkgconfig(ibus-1.0)
    - pkgconfig(xtst)
    - vala
    - meson
rundeps    :
    - gnome-session
    - gnome-settings-daemon
    - gnome-control-center
    - gnome-screensaver
description: |
    Budgie Desktop
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-typo-in-meson.build.patch
    %patch -p1 < $pkgfiles/0001-raven-If-the-text-is-escaped-already-don-t-escape-it.patch
    %patch -p1 < $pkgfiles/0001-raven-Only-deal-with-a-device-card-when-it-actually-.patch
    %patch -p1 < $pkgfiles/0002-raven-Mirror-the-last-fix-and-ensure-removed-Things-.patch
    %patch -p1 < $pkgfiles/0003-wm-Purge-old-backgrounds-from-the-cache.patch
    %patch -p1 < $pkgfiles/0001-daemon-Fix-the-order-of-left-side-window-buttons.patch
    %meson_configure -Dwith-stateless=true
build      : |
    %meson_build
install    : |
    # meson is completely out of its mind on crack and can't deal with
    # non utf. srsly.
    export LANG=en_US.utf8
    export LC_ALL=en_US.utf8
    %meson_install
