name       : budgie-desktop
version    : 10.2.5
release    : 81
source     :
    - https://solus-project.com/sources/budgie-desktop-10.2.5.tar.xz : 78952f5bc8bdeeb5e2dd2c56996f5dc19e578e0187b745d143c280c168826d32
license    :
    - GPL-2.0
    - LGPL-2.1
summary    : Budgie Desktop
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libpulse-mainloop-glib)
    - pkgconfig(libmutter)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(upower-glib)
    - pkgconfig(libgnome-menu-3.0)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gnome-bluetooth-1.0)
    - pkgconfig(gtk-doc)
    - vala
rundeps    :
    - gnome-session
    - gnome-settings-daemon
    - gnome-control-center
    - gnome-screensaver
ccache     : no
description: |
    Budgie Desktop
setup      : |
    %patch -p1 < $pkgfiles/0001-polkit-Ensure-to-set-an-icon.patch
    %patch -p1 < $pkgfiles/0002-Incorporate-a-GNOME-Screensaver-autostart-thanks-to-.patch
    %patch -p1 < $pkgfiles/0001-Hopefully-fix-update-issue-with-battery.patch
    %patch -p1 < $pkgfiles/0002-Forcibly-redraw-the-power-applet.patch
    %patch -p1 < $pkgfiles/0003-Try-to-brute-force-the-notify-signal.patch
    %patch -p1 < $pkgfiles/0004-Remove-spam-and-clean-it-up.patch
    %reconfigure --disable-static --enable-stateless
build      : |
    %make
install    : |
    %make_install
