name       : budgie-desktop
version    : 10.6.4
release    : 251
source     :
    - https://github.com/BuddiesOfBudgie/budgie-desktop/releases/download/v10.6.4/budgie-desktop-v10.6.4.tar.xz : 7775699ea64d7317e4004b751ccd5ab1e38df172ce17abc241b8a22bb31c1cdb
homepage   : https://blog.buddiesofbudgie.org
license    :
    - GPL-2.0-only
    - LGPL-2.1-only
summary    : Budgie Desktop is the flagship desktop experience developed by the Solus team.
description: |
    Budgie Desktop is the flagship desktop experience developed by the Solus team.
component  : desktop.budgie
builddeps  :
    - pkgconfig(accountsservice)
    - pkgconfig(alsa)
    - pkgconfig(gnome-bluetooth-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gnome-settings-daemon)
    - pkgconfig(gtk-doc)
    - pkgconfig(ibus-1.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libgnome-menu-3.0)
    - pkgconfig(libmutter-11)
    - pkgconfig(libnotify)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(libpulse-mainloop-glib)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(upower-glib)
    - budgie-screensaver # Required at configure time to ensure we have a proper configuration of budgie-desktop
    - vala
    - sassc
rundeps    :
    - budgie-control-center
    - budgie-desktop-view
    - budgie-screensaver
    - gnome-bluetooth-1-common
    - gnome-session
    - gnome-settings-daemon
    - network-manager-applet
    - xdotool
setup      : |
    %patch -p1 < $pkgfiles/0001-Remove-numeric-space-in-formatted-clock.patch
    %meson_configure -Dwith-stateless=true
build      : |
    %ninja_build
install    : |
    %ninja_install
