name        : budgie-desktop
version     : 8.3
release     : 60
source     :
    - https://github.com/solus-project/budgie-desktop/releases/download/v8.3/budgie-desktop-8.3.tar.xz : 21a1c46b59e10f8ffd720a8e5a1e8ef31a1a18ed935324f5e43da89a2981609f
license     :
    - GPL-2.0
summary     : Budgie Desktop
builddeps   :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libpulse-mainloop-glib)
    - pkgconfig(libmutter)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(upower-glib)
    - pkgconfig(libgnome-menu-3.0)
    - pkgconfig(gee-0.8)
    - pkgconfig(libpeas-1.0)
    - vala
ccache      : no
description : |
    Budgie Desktop
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
