name       : budgie-desktop
version    : 10.2.7
release    : 101
source     :
    - https://solus-project.com/sources/budgie-desktop-10.2.7.tar.xz : 1a8117bf66d52b0c50e57f626003c2ec658f47a9af2c03c6021fe4de755f068d
license    :
    - GPL-2.0
    - LGPL-2.1
summary    : Budgie Desktop
builddeps  :
    - pkgconfig(accountsservice)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libpulse-mainloop-glib)
    - pkgconfig(libmutter)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(upower-glib)
    - pkgconfig(libgnome-menu-3.0)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gnome-bluetooth-1.0)
    - pkgconfig(gtk-doc)
    - pkgconfig(ibus-1.0)
    - vala
rundeps    :
    - gnome-session
    - gnome-settings-daemon
    - gnome-control-center
    - gnome-screensaver
description: |
    Budgie Desktop
setup      : |
    %configure --disable-static --enable-stateless
build      : |
    %make
install    : |
    %make_install
