name       : budgie-desktop
version    : 10.2.9
release    : 112
source     :
    - https://github.com/budgie-desktop/budgie-desktop/releases/download/v10.2.9/budgie-desktop-10.2.9.tar.xz : 80c49c462dffbc1af7e1264be5add7e11ff23909c715adeb0aa22129ac524c48
license    :
    - GPL-2.0
    - LGPL-2.1
summary    : Budgie Desktop
component  : desktop.budgie
builddeps  :
    - pkgconfig(accountsservice)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libpulse-mainloop-glib)
    - pkgconfig(libmutter-0)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(upower-glib)
    - pkgconfig(libgnome-menu-3.0)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gnome-bluetooth-1.0)
    - pkgconfig(gtk-doc)
    - pkgconfig(ibus-1.0)
    - pkgconfig(xtst)
    - vala
rundeps    :
    - gnome-session
    - gnome-settings-daemon
    - gnome-control-center
    - gnome-screensaver
description: |
    Budgie Desktop
setup      : |
    %patch -p1 < $pkgfiles/0001-panel-Restore-missing-animations-GTK-3.22.patch
    sed -i 's:libmutter >= mutter_required_version:libmutter-0 >= mutter_required_version:g' configure.ac
    %reconfigure --disable-static --enable-stateless
build      : |
    %make
install    : |
    %make_install
