name        : budgie-desktop
version     : 8.2
release     : 54
source      :
    - https://solus-project.com/sources/budgie-desktop-8.2.tar.xz : 312774da3020805c542a1f4e2eb42931c5ee7cc4f2d58c6cef62c3ef2202b8a3
homepage    : https://solus-project.com
license     :
    - GPL-2.0
summary     : Budgie Desktop
builddeps   :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libpulse-mainloop-glib)
    - pkgconfig(libmutter)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(upower-glib)
    - pkgconfig(libgnome-menu-3.0)
    - pkgconfig(gee-0.8)
    - pkgconfig(libpeas-1.0)
    - vala
description : |
    Budgie Desktop
setup      : |
    %patch -p1 < $pkgfiles/0001-session-Force-gnome-as-XDG_CURRENT_DESKTOP-when-abse.patch
    %patch -p1 < $pkgfiles/0002-session-Make-Java-Google-Chrome-and-XDG-happy-by-lyi.patch
    %patch -p1 < $pkgfiles/0003-session-XDG_CURRENT_DESKTOP-is-case-sensitive.-Whoda.patch
    %patch -p1 < $pkgfiles/0001-Undo-insanity-broke-gnome-screenshot-i.patch
    %patch -p1 < $pkgfiles/0001-wm-Adapt-to-GSD-3.16-changes-closes-issue-204.patch
    %configure
build      : |
    %make
install    : |
    %make_install
