name       : budgie-desktop
version    : 10.5.1
release    : 214
source     :
    - git|https://github.com/solus-project/budgie-desktop.git : f2ab2f9cc9c16891cc05094d7669df172e8bd71a
license    :
    - GPL-2.0-only
    - LGPL-2.1-only
summary    : Budgie Desktop is the flagship desktop experience developed by the Solus team.
description: |
    Budgie Desktop is the flagship desktop experience developed by the Solus team.
component  : desktop.budgie
builddeps  :
    - pkgconfig(accountsservice)
    - pkgconfig(alsa)
    - pkgconfig(gnome-bluetooth-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gnome-settings-daemon)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk-doc)
    - pkgconfig(ibus-1.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libgnome-menu-3.0)
    - pkgconfig(libmutter-6)
    - pkgconfig(libnotify)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(libpulse-mainloop-glib)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(upower-glib)
    - pkgconfig(xtst)
    - vala
    - sassc
rundeps    :
    - gnome-session
    - gnome-settings-daemon
    - gnome-screensaver
setup      : |
    %meson_configure -Dwith-stateless=true -Dwith-desktop-icons=nautilus
build      : |
    %ninja_build
install    : |
    %ninja_install
