name       : budgie-desktop
version    : 10.2.7
release    : 93
source     :
    - https://github.com/solus-project/budgie-desktop/releases/download/v10.2.7/budgie-desktop-10.2.7.tar.xz : abfd35666764fabc39960dd298834e52d5cd7d7f2f3e1b5de77cfe1fe9090bad
license    :
    - GPL-2.0
    - LGPL-2.1
summary    : Budgie Desktop
builddeps  :
    - pkgconfig(accountsservice)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libpulse-mainloop-glib)
    - pkgconfig(libmutter)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(upower-glib)
    - pkgconfig(libgnome-menu-3.0)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gnome-bluetooth-1.0)
    - pkgconfig(gtk-doc)
    - vala
rundeps    :
    - gnome-session
    - gnome-settings-daemon
    - gnome-control-center
    - gnome-screensaver
ccache     : no
description: |
    Budgie Desktop
setup      : |
    %configure --disable-static --enable-stateless
build      : |
    %make
install    : |
    %make_install
