name        : budgie-desktop
version     : 10.2.1
release     : 64
source     :
    - https://github.com/solus-project/budgie-desktop/releases/download/v10.2.1/budgie-desktop-10.2.1.tar.xz : 693210996d5286f4d623900b3bdf6e1882ad237c18cffba95a4d0dce68960b81
license     :
    - GPL-2.0
summary     : Budgie Desktop
builddeps   :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libpulse-mainloop-glib)
    - pkgconfig(libmutter)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(upower-glib)
    - pkgconfig(libgnome-menu-3.0)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gsettings-desktop-schemas)
    - vala
rundeps     :
    - gnome-session
    - gnome-settings-daemon
    - gnome-control-center
ccache      : no
description : |
    Budgie Desktop
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
