name        : budgie-desktop
version     : 10.2.5
release     : 74
source     :
    - https://github.com/solus-project/budgie-desktop/releases/download/v10.2.5/budgie-desktop-10.2.5.tar.xz : 65bc36c67e4b0a68997fcd27b4c9058031f50b1b91d4b19923bf14f6b443b154
license     :
    - GPL-2.0
summary     : Budgie Desktop
builddeps   :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libpulse-mainloop-glib)
    - pkgconfig(libmutter)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(upower-glib)
    - pkgconfig(libgnome-menu-3.0)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gnome-bluetooth-1.0)
    - pkgconfig(gtk-doc)
    - vala
rundeps     :
    - gnome-session
    - gnome-settings-daemon
    - gnome-control-center
ccache      : no
description : |
    Budgie Desktop
setup      : |
    %patch -p1 < $pkgfiles/default-pins.patch
    autoreconf -vfi
    %configure --disable-static --enable-stateless
build      : |
    %make
install    : |
    %make_install
