name       : budgie-desktop
version    : 10.2.7
release    : 102
source     :
    - https://solus-project.com/sources/budgie-desktop-10.2.7.tar.xz : 8c7efda9342e6ce1bf9ac85351752c866d7b2a3411bd4395e30fec219fad3635
license    :
    - GPL-2.0
    - LGPL-2.1
summary    : Budgie Desktop
builddeps  :
    - pkgconfig(accountsservice)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libpulse-mainloop-glib)
    - pkgconfig(libmutter)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(upower-glib)
    - pkgconfig(libgnome-menu-3.0)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gnome-bluetooth-1.0)
    - pkgconfig(gtk-doc)
    - pkgconfig(ibus-1.0)
    - vala
rundeps    :
    - gnome-session
    - gnome-settings-daemon
    - gnome-control-center
    - gnome-screensaver
description: |
    Budgie Desktop
setup      : |
    %configure --disable-static --enable-stateless
build      : |
    %make
install    : |
    %make_install
