name       : budgie-desktop
version    : 10.7.2
release    : 256
source     :
    - https://github.com/BuddiesOfBudgie/budgie-desktop/releases/download/v10.7.2/budgie-desktop-v10.7.2.tar.xz : cce9ebe21b4bba4886bb2a227d739b7340c35085f08c132d3d8ae6b6621ba7b4
homepage   : https://blog.buddiesofbudgie.org
license    :
    - GPL-2.0-only
    - LGPL-2.1-only
summary    : Budgie Desktop is the flagship desktop experience developed by the Solus team.
description: |
    Budgie Desktop is the flagship desktop experience developed by the Solus team.
component  : desktop.budgie
builddeps  :
    - pkgconfig(accountsservice)
    - pkgconfig(alsa)
    - pkgconfig(gee-0.8)
    - pkgconfig(gnome-bluetooth-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gnome-settings-daemon)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gtk-doc)
    - pkgconfig(ibus-1.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libcanberra)
    - pkgconfig(libmutter-11)
    - pkgconfig(libnotify)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(libpulse-mainloop-glib)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(upower-glib)
    - budgie-screensaver # Required at configure time to ensure we have a proper configuration of budgie-desktop
    - vala
    - sassc
rundeps    :
    - budgie-control-center
    - budgie-screensaver
    - gnome-bluetooth-1-common
    - gnome-session
    - gnome-settings-daemon
    - network-manager-applet
    - xdotool
setup      : |
    %meson_configure -Dwith-stateless=true -Duse-old-zenity=true
build      : |
    %ninja_build
install    : |
    %ninja_install
