name       : budgie-desktop
version    : 10.2.6
release    : 89
source     :
    - https://github.com/solus-project/budgie-desktop/releases/download/v10.2.6/budgie-desktop-10.2.6.tar.xz : 88febba5dbf5456a1573753be836d17c261971ccefcb4b56370b5bf053e9b659
license    :
    - GPL-2.0
    - LGPL-2.1
summary    : Budgie Desktop
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libpulse-mainloop-glib)
    - pkgconfig(libmutter)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(upower-glib)
    - pkgconfig(libgnome-menu-3.0)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gnome-bluetooth-1.0)
    - pkgconfig(gtk-doc)
    - vala
rundeps    :
    - gnome-session
    - gnome-settings-daemon
    - gnome-control-center
    - gnome-screensaver
ccache     : no
description: |
    Budgie Desktop
setup      : |
    %patch -p1 < $pkgfiles/0001-Add-Zim-as-a-derper.patch
    %patch -p1 < $pkgfiles/0002-theme-Ensure-we-link-against-GTK-issue-465.patch
    %patch -p1 < $pkgfiles/0004-Sync-translations.patch
    %patch -p1 < $pkgfiles/0005-wm-Trial-inclusion-of-force-unredirect-configuration.patch
    %patch -p1 < $pkgfiles/0006-applets-icon-tasklist-Ensure-pin-items-are-actually-.patch
    %patch -p1 < $pkgfiles/0008-wm-Fix-yesterdays-cruft-with-unredirect.patch
    %configure --disable-static --enable-stateless
build      : |
    %make
install    : |
    %make_install
